[package]
name = "strange-attractors"
version = "0.1.0"
description = "fast geometry generation for strange attractors"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
nalgebra-glm = "0.15.0"
